### ISSUE TITLE
Create & Manage Retention Policy 

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/influxdb#10]
Retention policies affect how measurements are stored and interact with databases. Mount API shall be updated to support creating, reading (selecting), updating, and deleting retention policies.

**Comment by SanderMertens** [comment]
Can you elaborate on this? How retention policies are specified can be pretty specific to a datastore (is it specified on date, measurement, value.. and with a fixed interval or by using some kind of LOD algorithm etc).

I think this potentially touches upon a more fundamental requirement, which is to enable passing down technology-specific configuration to mounts. Some initial design work has been done on this (this was in the context of the DDS mount), where a user could do something like this:

```c
// Require all data matching the query to be persistent
bool success = corto_select("//foo|bar").require("persistent=true");
```
The return value of this function would tell the applications whether the mounts providing the objects matching the query are able to support persistency. This way the separation between application code and mounts is still maintained, and the requirements are specified on data.

A similar thing could be done for retention policies. The `require` method would accept a key-value pair which I think should allow for enough flexibility.

In the short term, a more static solution would be to add a retention policy as member to the `influx` mount.

**Comment by hendrenja** [comment]
My understanding of the configuration that an app would want to pass to a mount when querying data is unclear. Why does the app care if Data has persistent Quality of Service? I don't want to pick on the DDS example, but wouldn't it be the middleware that would tell the app when data is no longer invalid? In a DDS app, I'm going to hold data and assume it's good until I get a quality update for DDS. In the Corto world, I understand this to eventually be the expiry notification from the cache (in the future). 

Zooming out, larger than DDS, I interpret `persistence=true` to be a general quality guarantee for the data. This could also be applied to something like a _MongoDB Mount_, right?

If I am understanding this correctly, then I think this is a slightly different use case than InfluxDB's retention policies can provide. Retention policies affect the data structure and data management that InfluxDB provides on the backend. Per InfluxDB documentation:

> The part of InfluxDB’s data structure that describes for how long InfluxDB keeps data (duration), how many copies of those data are stored in the cluster (replication factor), and the time range covered by shard groups (shard group duration). RPs are unique per database and along with the measurement and tag set define a series.

I am going to move forward with the static implementation for now. I am not sure what happens when you attempt to change a measurement's or database's retention policy midway once it has already been created. That still needs be tested. 

**Retention Policy**
```
class RetentionPolicy:/
    name:           string
    duration:       string
    replication:    uint16
    shardDuration:  string
```

**InfluxDB Mount** _Update_
```
class Mount: vstore/mount:/
    host:       string
    db:         string
    rp:         influxdb/RetentionPolicy, optional
    username:   string
    password:   string
```

- If `NULL`, then the default `autogen` retention policy will be used. 
- The specified Retention Policy will be provided on each write, instead of being specified as the default retention policy.

**Comment by SanderMertens** [comment]
@hendrenja In some cases the functionality of an application will rely on whether certain non-functional aspects are guaranteed, even though it does not necessarily affect the code.

An example: an application can read/write objects without knowing whether they will be persisted to disk, but the application might not work correctly if data is *not* persisted to disk. In this case, the application can let corto know that it is expecting the data to be stored somewhere.

Another example would be security. If an application is sending sensitive information, it could "require" that whatever mount is going to handle this data does so securely. If a mount cannot provide this capability, it should not attempt to send the data.

Both examples show how an application can ensure that even though its business logic can be ran unchanged against different configurations, those configurations still have to meet certain (minimal) requirements.

In the case of retention, an application requesting historical data could for example require that the data is stored with a downsampling period of at most 1 day. If the active retention policy is less than that, the application's algorithms may for example not function correctly or produce results that are not of sufficient accuracy.

The difference between configuration and app requirements is that the configuration describes the infrastructure against which applications are ran. A single application can be ran against multiple infrastructures, and this is a mechanism to ensure that both match, without creating a direct coupling between a specific mount and application.

You are right that something like persistence can be used for multiple kinds of storages. I expect that a library of "requirements" will grow over time that mounts can choose to implement or not.

**Comment by hendrenja** [comment]
@SanderMertens, I better understand your original comment now. 
```
// Require all data matching the query to be persistent
bool success = corto_select("//foo|bar").require("persistent=true");
```

Could be expanded to something like...
```
// Require all data matching the query to be persistent
bool success = corto_select("//foo|bar")
    .require("persistent=true","frequency=10Hz","resolution=8h")
    .where("time<2h");
```
... to specify the algorithm requires *persistent* data samples stored every *100ms* across the last *8 hours*. The `Where` expression may only require the last 2 hours of data, but it would require that the data source 8 hours of 10Hz data available. 

Am I appropriately grasping data requirements?

**Comment by SanderMertens** [comment]
@hendrenja You got it! :)
